export const Users = [
    {
        id:1,
        profilePicture: "assets/tfue.jpg",
        username: "Ajes Nielsen",
    },
    {
        id:2,
        profilePicture: "assets/ph.png",
        username: "Torben Jensen",
    },
    {
        id:3,
        profilePicture: "assets/ph.png",
        username: "Frederik Christensen",
    },
    {
        id:4,
        profilePicture: "assets/glassesEmoji.png",
        username: "Ib Ibsen",
    },
    {
        id:5,
        profilePicture: "assets/ph.png",
        username: "Niels Nielen",
    },
    {
        id:6,
        profilePicture: "assets/glassesEmoji.png",
        username: "Frank Franksen",
    },
    {
        id:7,
        profilePicture: "assets/glassesEmoji.png",
        username: "Kirsten Kirstensen",
    },
    {
        id:8,
        profilePicture: "assets/ph.png",
        username: "Marlene Marlenesen",
    },
]

export const Posts = [
    {
        id: 1,
        desc: "Jeg leder efter en lejlighed i nærheden af...",
        photo: "assets/ph.png",
        date: "5 mins ago",
        userId: 1,
        like: 22,
        comment: 9,
    },
    {
        id: 2,
        desc: "I dag har jeg været ude at gå med min....",
        photo: "assets/ph.png",
        date: "23 mins ago",
        userId: 2,
        like: 222,
        comment: 79,
    },
    {
        id: 3,
        photo: "assets/ph.png",
        date: "29 mins ago",
        userId: 3,
        like: 32,
        comment: 55,
    },
    {
        id: 4,
        desc: "Det er et godt vejr i dag!",
        photo: "assets/ph.png",
        date: "35 mins ago",
        userId: 4,
        like: 21,
        comment: 900,
    },
    {
        id: 5,
        desc: "Lækkert mad",
        photo: "assets/ph.png",
        date: "43 mins ago",
        userId: 5,
        like: 5,
        comment: 14,
    },
    {
        id: 6,
        photo: "assets/ph.png",
        date: "59 mins ago",
        userId: 6,
        like: 18,
        comment: 19,
    },
    {
        id: 7,
        photo: "assets/ph.png",
        date: "2 days ago",
        userId: 7,
        like: 99,
        comment: 1,
    },
    {
        id: 8,
        desc: "lolleren mand",
        photo: "assets/ph.png",
        date: "5 days ago",
        userId: 8,
        like: 1000,
        comment: 2,
    },
]